apiVersion: v1
kind: Service
metadata:
  name: vpa-recommender
  labels:
    app: vpa-recommender
spec:
  selector:
    app.kubernetes.io/name: vpa
  ports:
    - name: metrics
      port: 8942
      targetPort: 8942
