apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vpa-recommender
  labels:
    release: kps  # Match your Prometheus Operator's `serviceMonitorSelector`
spec:
  selector:
    matchLabels:
      app: vpa-recommender
  endpoints:
    - port: metrics
      interval: 30s

